snowflake:
  machine-id: 1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/snowflakeid?reWriteBatchedInserts=true
#    username: bnagpal
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
#      show-sql: true
  main:
    allow-circular-references: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE